name: CUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            build-essential \
            libcunit1 \
            make \
            xorg-dev \
            wget \
            tar \
            autoconf \
            libc6-dev \
            libx11-dev \
            libxext-dev \
            libclang-dev \
            libpthread-stubs0-dev \
            git \
            libbsd-dev

      - name: Set environment variables
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CFLAGS=-Wall -Wextra -Werror -Wuninitialized -g -pthread -mavx -Ofast -march=native -ffunction-sections -finline-functions -I$(HEADERS_DIRECTORY) -I$(LIBFT_DIRECTORY) -I$(MLX_DIRECTORY) -I$(CUNIT_DIRECTORY)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-lc" >> $GITHUB_ENV
    
      - name: Build project
        run: |
          make clean
          make all

      - name: Run tests
        run: |
          make test
