name: CUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            gcc \
            libc6-dev \
            gawk

      - name: Download and build CUnit
        run: |
            CUNIT_DIR=lib/cunit
            if [ ! -d "$CUNIT_DIR" ]; then
            echo "CUnit not found! Downloading and building..."
            mkdir -p lib && cd lib
            wget https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
            tar -xvf CUnit-2.1-3.tar.bz2
            mv CUnit-2.1-3 cunit
            rm CUnit-2.1-3.tar.bz2
            fi

            echo "Building CUnit..."
            cd $CUNIT_DIR
            autoreconf -fi
            ./configure --prefix="$(pwd)"
            make -j$(nproc)
            make install

            echo "CUnit compiled and installed"
                cd lib/cunit
                autoreconf -fi
                [ -f configure.in ] && mv configure.in configure.ac
                autoupdate

                ./configure CFLAGS="-O2" LDFLAGS="-lc" || (cat config.log && exit 1)
                make -j$(nproc)

      - name: Clone and compile MiniLibX
        run: |
          if [ ! -d "lib/minilibx-linux" ]; then
            git clone https://github.com/42Paris/minilibx-linux lib/minilibx-linux
          fi
          cd lib/minilibx-linux
          make

      - name: Compile Libft
        run: |
          if [ ! -d "lib/libft" ]; then
            git clone https://github.com/42Paris/libft lib/libft
          fi
          cd lib/libft
          make

      - name: Build and run tests with flags
        run: |
          make fclean
          make test CFLAGS="-Werror -Iinclude"
