name: CUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libc6-dev \
            libcunit1 \
            make \
            gcc \
            gawk \
            xorg-dev \
            wget \
            tar \
            autoconf \
            libx11-dev \
            libxext-dev \
            git \
            libbsd-dev \
            automake \
            libtool \
            pkg-config \
            libc-dev

      - name: Clone and compile MiniLibX
        run: |
          if [ ! -d "lib/minilibx-linux" ]; then
            git clone https://github.com/42Paris/minilibx-linux lib/minilibx-linux
          fi
          cd lib/minilibx-linux
          make

      - name: Compile Libft
        run: |
          if [ ! -d "lib/libft" ]; then
            git clone https://github.com/42Paris/libft lib/libft
          fi
          cd lib/libft
          make

      - name: Build and run tests with flags
        run: |
          make fclean
          make test CFLAGS="-Werror -Iinclude"
